# Generated by Django 5.2.6 on 2025-09-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите полный текст цитаты', verbose_name='Текст цитаты')),
                ('philosopher_name', models.CharField(help_text='Введите автора цитаты', max_length=100, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'бусина',
                'verbose_name_plural': 'бусины',
                'ordering': ['philosopher_name'],
            },
        ),
    ]
